#spring.application.name=eureka-comsumer
#server.port=9094
#
##eureka.client.serviceUrl.defaultZone = http://39.98.36.217:8761/eureka/
#eureka.client.serviceUrl.defaultZone = http://127.0.0.1:8761/eureka/


feign:
  hystrix:
    enabled: true

spring:
  application:
    name: eureka-comsumer
server:
  port: 9094

#eureka.client.serviceUrl.defaultZone = http://39.98.36.217:8761/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/	


